#theme: "jekyll-theme-hacker"
#remote_theme: "P0WEX/Gesko"
#remote_theme: "Trybnetic/minimalist"
remote_theme: "piharpi/jekyll-klise"
title: "WC96's Developer Blog"
description: "Keeping track of progress during the 2022 Learn Jam!"
